### ISSUE TITLE
Upgrade from v1.0

### ISSUE THREAD

**Issue by denver-s** [midl-dev/tezos-on-gke#23]
Hello, is there a guide on how to safely upgrade from v1.0?

I am mostly concerned about the v1.0 signer which is probably not compatible with the v1.1 cloud baker.

Do I need to upgrade one of the two signers, then setup a v1.1 cloud baker connected to the upgraded signer and then stop the v1.0 baker (in order to avoid double baking) once I see that everything is working fine?

**Comment by hodl-dot-farm** [comment]
I do not have a formal upgrade guide yet, so your feedback is welcome.

First, I would say, switch off one of the 2 signers. Literally remove the
ledger if you can, for the duration of the upgrade. You do not want to be
in the situation where you may equivocate.

Indeed, the 1.0 signer is incompatible with 1.1 load balancer. The wrapper
script is performing more extensive checks (specifically, that the ledger
is connected and ready to sign) so the status url is different.

You can install the wrapper script and run it on a different port. That
will not interrupt operations.

Spin up a fresh 1.1 cluster and wait for it to sync.

Then change the target hostname of the forwarder unit file, as well as the
local port being forwarded. Wait for a quiet time with no bakes/endorses,
then restart the tezos-signer-forwarder daemon. The alert should clear on
the new cluster, and the new cluster will now be the one broadcasting your
signed operations.

Once done, destroy the old cluster, then migrate the second signer.

This is how I did it anyway. The 1.1 signer should work on the 1.0 load
balancer, so you may also have an intermediate step where your 1.0 setup
targets the 1.1 signer wrapper instead of the signer directly.

Also, the wrapper script expects a raspberry pi with one specific model of
ups hat and two network ports (eth0/eth1), so if you setup is not exactly
as described, you may need to modify the script.

I hope this helps.
